data:
    dataset_type: "cached_threedfront"
    room_type: "livingroom"
    encoding_type: "cached"
    dataset_directory: "../dump/livingroom"
    annotation_file: "../config/livingroom_threed_front_splits.csv"
    room_type_filter: "no_filtering"
    train_stats: "dataset_stats.txt"
    room_layout_size: "256,256"
    num_each_class: 4
    num_class: 23
    data_dim: 16
    half_range: 6
    interval: 0.3

training:
    splits: ["train", "val"]
    tag: "livingroom_ebvae_h32_mss"
    checkpoint_dir: "../savepoint"
    epochs: 1000
    batch_size: 16
    save_frequency: 50
    optimizer: Adam
    lr: 0.001
    weight_decay: 0
    adjust_kl_divergence: false

validation:
    splits: ["test"]
    frequency: 5
    batch_size: 16

generate:
    output_path: '../output/'

EnhancedBetaTCVAE:
    input_dim: 16
    latent_dimension: 32
    bn_momentum: 0.0005
    kld_weight: 0.0001
    kld_interval: 50

    sparse_num: 4

    embedding_dim1: 32
    embedding_dim2: 48
    embedding_dim3: 64

    sparse_embedding1: 256
    sparse_embedding2: 128
    sparse_embedding3: 64

    linear_embedding1: 32
    linear_embedding2: 16
    linear_embedding3: 4

UNet3Plus:
    input_dim: 16
    bn_momentum: 0.01
    embedding_dim1: 64
    embedding_dim2: 128
    embedding_dim3: 256
    embedding_dim4: 512
